### ISSUE TITLE
VisualPlugins on ros2 branch that are loaded in both gzserver and gzclient have non-unique ROS node names

### ISSUE THREAD

**Issue by scpeters** [nasa/irg_open#15]
Gazebo VisualPlugins can be loaded in both `gzserver`'s camera sensor rendering thread and `gzclient`'s user camera rendering thread. Some of the VisualPlugins in `irg_gazebo_plugins` on the `ros2` branch use `gazebo_ros::Node::Get(_sdf)` to initialize a ROS 2 node for the plugin (such as [LinkTracksPlugin](https://github.com/nasa/irg_open/blob/ros2/irg_gazebo_plugins/src/IRGLinkTracksPlugin/LinkTracksPlugin.cpp#L53) and [GlobalShaderParamPlugin](https://github.com/nasa/irg_open/blob/ros2/irg_gazebo_plugins/src/IRGGlobalShaderParamPlugin/GlobalShaderParamPlugin.cpp#L62)). As called, this helper function sets the ROS node name from the plugins XML `name` attribute and will give the same name to ROS nodes associated with both `gzserver` and `gzclient`.

Currently many ROS 2 features and design assumptions depend on unique node names (https://github.com/ros2/design/issues/187), so it would be beneficial to follow that pattern. There is an overload of [gazebo_ros::Node::Get](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/ros2/gazebo_ros/include/gazebo_ros/node.hpp#L94) that accepts a `std::string` as a second parameter to use for the ROS node name, so it is straightforward to set this name programmatically.

Some approaches to name uniqueness include adding a random suffix (based on PID or time) to the node name or a suffix based on whether the plugin is loaded by `gzserver` or `gzclient`. One approach to determining whether a VisualPlugin is loaded by `gzserver` or `gzclient` is by checking the `RMT_PORT` environment variable (used for visualizing profiler data), which is set to `1500` in `gzserver`'s [server_main.cc](https://github.com/gazebosim/gazebo-classic/blob/gazebo11/gazebo/server_main.cc#L28) and 1501 in `gzclient`'s [main.cc](https://github.com/gazebosim/gazebo-classic/blob/gazebo11/gazebo/gui/main.cc#L26). This is not elegant, but would be straightforward to implement.

**Comment by mogumbo** [comment]
Resolved by merging a solution to the problem from a fork:
* https://github.com/nasa/irg_open/commit/2e0f14a7bbcca539306a6439fcd68775ca9be7e0
* https://github.com/nasa/irg_open/commit/f30fe842aee1ba31d5b84b5449fbe97087c8f1d3
